version: "3.8"

services:
  app:
    container_name: "${PROJECT_NAME}_react"
    image: "${PROJECT_NAME}-app-dev"
    environment:
      REACT_APP_NAME: $REACT_APP_NAME
    build:
      context: .
      target: development
      args:
        REACT_APP_NAME: $REACT_APP_NAME
    networks:
      - web
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    labels:
      # Enable handler entrypoint on http.
      - "traefik.http.routers.${DOCKER_NAME}_app-http.entrypoints=web"
      # Define handler http host.
      - "traefik.http.routers.${DOCKER_NAME}_app-http.rule=Host(`app.${DOCKER_BASE_URL}`)"
      # Define http middleware and redirection to https.
      - "traefik.http.routers.${DOCKER_NAME}_app-http.middlewares=${DOCKER_NAME}_app-https"
      - "traefik.http.middlewares.${DOCKER_NAME}_app-https.redirectscheme.scheme=https"
      # Enable handler entrypoint on https.
      - "traefik.http.routers.${DOCKER_NAME}_app.entrypoints=websecure"
      # Define handler host.
      - "traefik.http.routers.${DOCKER_NAME}_app.rule=Host(`app.${DOCKER_BASE_URL}`)"
      # Instructs Traefik that the current router is dedicated to HTTPS requests only.
      - "traefik.http.routers.${DOCKER_NAME}_app.tls=true"
      # Set service port for loadbalancer
      # - "traefik.http.services.${PROJECT_NAME}_app.loadbalancer.server.port=8080"
      # Define on which network Traefik is operating.
      - "traefik.docker.network=web"
networks:
  web:
    external: true
